-- =========================================================================
-- PaisaPOS schema snapshot deprecated
-- =========================================================================
--
-- This file is intentionally non-executable.
--
-- Do not paste this file into the Supabase SQL editor. It used to contain an
-- old bootstrap schema that predates staff management, activity events,
-- privilege delegations, RLS hardening, and service-role-only RPCs.
--
-- The canonical database history now lives in:
--
--   supabase/migrations/
--
-- To rebuild a local database, run:
--
--   supabase db reset --local
--
-- To inspect the current local schema, generate a fresh dump from the local
-- database and review it against the migrations before committing it.
--
-- Keeping this file as comments prevents accidental execution of stale SQL
-- while preserving the path for older documentation links.
